//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_grafovi
{
    using System;
    using System.Collections.Generic;
    
    public partial class cvor
    {
        public string username { get; set; }
        public int id { get; set; }
        public double posX { get; set; }
        public double posY { get; set; }
    
        public virtual korisnici korisnici { get; set; }
    }
}
