//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_grafovi
{
    using System;
    using System.Collections.Generic;
    
    public partial class konekcije
    {
        public string username { get; set; }
        public int startCvor { get; set; }
        public int endCvor { get; set; }
        public double tezina { get; set; }
    
        public virtual korisnici korisnici { get; set; }
    }
}
